// Language types matching backend LanguageType enum
export type LanguageType =
  | "ENGLISH"
  | "POLISH"
  | "GERMAN"
  | "FRENCH"
  | "SPANISH"
  | "ITALIAN"
  | "PORTUGUESE"
  | "DUTCH"
  | "RUSSIAN"
  | "CHINESE"
  | "JAPANESE"
  | "KOREAN"
  | "ARABIC"
  | "HINDI"
  | "TURKISH"
  | "SWEDISH"
  | "NORWEGIAN"
  | "DANISH"
  | "FINNISH"
  | "CZECH"
  | "UKRAINIAN"
  | "GREEK"
  | "HUNGARIAN"
  | "ROMANIAN"
  | "BULGARIAN"
  | "CROATIAN"
  | "SERBIAN"
  | "SLOVAK"
  | "SLOVENIAN"
  | "ESTONIAN"
  | "LATVIAN"
  | "LITHUANIAN"
  | "THAI"
  | "VIETNAMESE"
  | "INDONESIAN"
  | "MALAY"
  | "TAGALOG"
  | "BENGALI"
  | "URDU"
  | "PERSIAN"
  | "HEBREW"
  | "SWAHILI"
  | "AFRIKAANS"
  | "MANDARIN";

// Human-readable labels for each language
export const LANGUAGE_LABELS: Record<LanguageType, string> = {
  ENGLISH: "English",
  POLISH: "Polish",
  GERMAN: "German",
  FRENCH: "French",
  SPANISH: "Spanish",
  ITALIAN: "Italian",
  PORTUGUESE: "Portuguese",
  DUTCH: "Dutch",
  RUSSIAN: "Russian",
  CHINESE: "Chinese",
  JAPANESE: "Japanese",
  KOREAN: "Korean",
  ARABIC: "Arabic",
  HINDI: "Hindi",
  TURKISH: "Turkish",
  SWEDISH: "Swedish",
  NORWEGIAN: "Norwegian",
  DANISH: "Danish",
  FINNISH: "Finnish",
  CZECH: "Czech",
  UKRAINIAN: "Ukrainian",
  GREEK: "Greek",
  HUNGARIAN: "Hungarian",
  ROMANIAN: "Romanian",
  BULGARIAN: "Bulgarian",
  CROATIAN: "Croatian",
  SERBIAN: "Serbian",
  SLOVAK: "Slovak",
  SLOVENIAN: "Slovenian",
  ESTONIAN: "Estonian",
  LATVIAN: "Latvian",
  LITHUANIAN: "Lithuanian",
  THAI: "Thai",
  VIETNAMESE: "Vietnamese",
  INDONESIAN: "Indonesian",
  MALAY: "Malay",
  TAGALOG: "Tagalog",
  BENGALI: "Bengali",
  URDU: "Urdu",
  PERSIAN: "Persian",
  HEBREW: "Hebrew",
  SWAHILI: "Swahili",
  AFRIKAANS: "Afrikaans",
  MANDARIN: "Mandarin",
};

// Flag emoji for common languages (optional visual enhancement)
export const LANGUAGE_FLAGS: Partial<Record<LanguageType, string>> = {
  ENGLISH: "🇬🇧",
  POLISH: "🇵🇱",
  GERMAN: "🇩🇪",
  FRENCH: "🇫🇷",
  SPANISH: "🇪🇸",
  ITALIAN: "🇮🇹",
  PORTUGUESE: "🇵🇹",
  DUTCH: "🇳🇱",
  RUSSIAN: "🇷🇺",
  CHINESE: "🇨🇳",
  JAPANESE: "🇯🇵",
  KOREAN: "🇰🇷",
  ARABIC: "🇸🇦",
  HINDI: "🇮🇳",
  TURKISH: "🇹🇷",
  SWEDISH: "🇸🇪",
  NORWEGIAN: "🇳🇴",
  DANISH: "🇩🇰",
  FINNISH: "🇫🇮",
  CZECH: "🇨🇿",
  UKRAINIAN: "🇺🇦",
  GREEK: "🇬🇷",
  HUNGARIAN: "🇭🇺",
  ROMANIAN: "🇷🇴",
  MANDARIN: "🇨🇳",
};
