package pl.dayfit.auroracore.type

enum class EducationDegree {
    LOWER_SECONDARY_SCHOOL,
    UPPER_SECONDARY_SCHOOL,
    VOCATIONAL_SCHOOL,
    HIGH_SCHOOL,
    ASSOCIATE_DEGREE,
    BACHELOR_DEGREE,
    MASTER_DEGREE,
    DOCTORAL_DEGREE,
    POSTDOCTORAL,
    PROFESSIONAL_CERTIFICATE,
    OTHER
}