package pl.dayfit.auroraauth.configuration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration
import pl.dayfit.auroraauth.configuration.properties.JwtConfigurationProperties

@Configuration
@EnableConfigurationProperties(JwtConfigurationProperties::class)
class JwtConfiguration