FROM amazoncorretto:21-alpine3.22-jdk AS build

COPY aurora-auth/ /aurora/
WORKDIR /aurora
RUN chmod +x ./mvnw && \
    ./mvnw clean package -DskipTests

FROM amazoncorretto:21-al2023-headless
COPY --from=build /aurora/target/aurora-auth-*.jar /aurora/aurora-auth.jar
CMD ["java", "-jar", "/aurora/aurora-auth.jar"]
EXPOSE 8083