FROM amazoncorretto:21-alpine3.22-jdk

COPY aurora-core/ /aurora/
WORKDIR /aurora

RUN \
    chmod +x ./mvn && \
    chmod +x ./mvnw && \
    ./mvnw clean package -DskipTests && \
    mv target/aurora-core-*.jar /aurora/aurora-core.jar

CMD ["java", "-jar", "aurora-core.jar"]