FROM amazoncorretto:21-alpine3.22-jdk

COPY ./aurora-ai/ /aurora/

WORKDIR /aurora

RUN \
    chmod +x ./mvnw && \
    ./mvnw clean package -DskipTests && \
    mv /aurora/target/aurora-ai-*.jar /aurora/aurora-ai.jar

CMD ["java", "-jar", "/aurora/aurora-ai.jar"]

EXPOSE 8082