// aurora-front/src/lib/backend/get-autogenerated-resume.ts
import { callBackend } from "@/lib/backend/backend";
import { RequestMethod } from "@/lib/types/backend";

export default async function getAutogeneratedResume(autoGenerationId: string) {
  return await callBackend({
    endpoint: `/api/v1/core/autogeneration/${autoGenerationId}`,
    method: RequestMethod.GET,
    baseUrl: process.env.BACKEND_CORE_URL,
  });
}
