// aurora-front/src/lib/backend/get-autogenerated-resume.ts
import { callBackend } from "@/lib/backend/backend";
import { RequestMethod } from "@/lib/types/backend";
import { ApiService } from "@/lib/backend/api-config";

export default async function getAutogeneratedResume(autoGenerationId: string) {
  return await callBackend({
    endpoint: `/api/v1/core/autogeneration/${autoGenerationId}`,
    method: RequestMethod.GET,
    service: ApiService.CORE,
  });
}
