// aurora-front/src/components/cv-components/tracker-notification.tsx
"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { IoSync, IoClose, IoCheckmark } from "react-icons/io5";
import { useTracker } from "@/context/tracker-context";
import { useRouter } from "next/navigation";
import getAutogeneratedResume from "@/lib/backend/get-autogenrated-resume";

export default function TrackerNotification() {
  const { isTracking, trackingId, autoGenerationId, stopTracking } =
    useTracker();
  const [status, setStatus] = useState<string>("Initializing...");
  const [step, setStep] = useState<number>(1);
  const [isFinished, setIsFinished] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (!isTracking || !trackingId) return;

    setIsFinished(false);
    setStatus("Connecting...");
    setStep(1);

    const socket = new WebSocket(
      `ws://localhost:8081/api/v1/core/ws/tracker/${trackingId}`,
    );

    socket.onopen = () => {
      setStatus("Connected, processing...");
    };

    socket.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        setStatus(data.status || "Processing...");
        setStep(data.step || 1);
        if (data.finished) {
          setIsFinished(true);
          socket.close();
        }
      } catch {
        setStatus(event.data);
      }
    };

    socket.onerror = () => {
      setStatus("Connection error");
    };

    socket.onclose = () => {
      if (!isFinished) {
        setStatus("Connection closed");
      }
    };

    return () => {
      if (socket.readyState === WebSocket.OPEN) {
        socket.close();
      }
    };
  }, [isTracking, trackingId]);

  const handleFinish = async () => {
    if (!isFinished) return;

    setIsLoading(true);
    try {
      if (autoGenerationId) {
        // Fetch the generated resume
        const { status, data } = await getAutogeneratedResume(autoGenerationId);
        if (status === 200 && data) {
          router.refresh();
        }
      }
      stopTracking();
      router.refresh();
    } catch (error) {
      console.error("Error fetching result:", error);
    } finally {
      setIsLoading(false);
    }
  };

  if (!isTracking) return null;

  const getStepColor = () => {
    if (isFinished) return "bg-aurora-green-dark";
    if (step === 1) return "bg-aurora-blue-dark";
    if (step === 2) return "bg-aurora-purple-dark";
    return "bg-aurora-green-dark";
  };

  return (
    <AnimatePresence>
      {isTracking && (
        <motion.div
          initial={{ opacity: 0, y: 50, scale: 0.9 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 50, scale: 0.9 }}
          className={`fixed bottom-6 right-6 p-4 rounded-2xl shadow-2xl z-50 flex items-center gap-4 text-white min-w-[300px] transition-colors duration-500 ${getStepColor()} ${isFinished ? "cursor-pointer" : ""}`}
          onClick={isFinished ? handleFinish : undefined}
        >
          <div className="flex flex-col flex-1">
            <span className="text-xs font-medium opacity-80 uppercase">
              {isFinished ? "Click to complete" : `Step ${step} of 3`}
            </span>
            <span className="text-sm font-bold">
              {isLoading ? "Loading..." : status}
            </span>
          </div>
          {isFinished ? (
            <IoCheckmark className="text-2xl" />
          ) : (
            <IoSync className="text-2xl animate-spin" />
          )}
          <button
            onClick={(e) => {
              e.stopPropagation();
              stopTracking();
            }}
            className="ml-2 opacity-50 hover:opacity-100"
          >
            <IoClose size={20} />
          </button>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
